"""add_couple_table

Revision ID: c74668935352
Revises: c273e9da4fff
Create Date: 2020-09-12 12:10:42.976341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74668935352'
down_revision = 'c273e9da4fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'couple',
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lead_id', sa.Integer(), nullable=True),
        sa.Column('follow_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['follow_id'], ['person.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['lead_id'], ['person.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('lead_id', 'follow_id', name='_lead_follow_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('couple')
    # ### end Alembic commands ###
