TABLE_USERS = "users"
TABLE_ROLES = "roles"
TABLE_USER_ROLE = "user_role"
TABLE_DANCING_CLASS = "dancing_class"
TABLE_PERSON = "person"
TABLE_DANCING_CLASS_PERSON = "dancing_class_person"
TABLE_DANCING_CLASS_COUPLE = "dancing_class_couple"
TABLE_COUPLE = "couple"
